[[neper]]
arch = "aarch64"
git-tree-sha1 = "51b7e3f902f996c4534cd6f355ac611fa36f7fdc"
os = "macos"

    [[neper.download]]
    sha256 = "f334ec8e5cb4aa6dd82ffd0828a503bb3f2fb07471d7186f37fdef5b268ee06c"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.aarch64-apple-darwin.tar.gz"
[[neper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e21c493d65641b2efa6c61f2fca677d53eaba243"
libc = "glibc"
os = "linux"

    [[neper.download]]
    sha256 = "756f04df73ec7339bac76fb1c52a4903769fc218e5169cfb7ba60098c76ce365"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.aarch64-linux-gnu-cxx03.tar.gz"
[[neper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4433dd9559aa993677ce41b380232ec9183cd4ff"
libc = "glibc"
os = "linux"

    [[neper.download]]
    sha256 = "a1b156c25ee3c4e1f04d122395b9ecf3878f5a9a5958b4543b61a0e403ff074c"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.aarch64-linux-gnu-cxx11.tar.gz"
[[neper]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "914fd4001094a37db82d95c042f76bbd5fb9215d"
libc = "glibc"
os = "linux"

    [[neper.download]]
    sha256 = "dbb783f1b868eda54c723acae7c11400582034cb90ff9e47fc7e58f2ba707c4e"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[neper]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c5751c7473279b6b6cbf51e7b9d3eb25aa3e405"
libc = "glibc"
os = "linux"

    [[neper.download]]
    sha256 = "e67738b5d10a107a724e9ac615ba6b310e9239aa8e47eaf15a70d51e77877e6d"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[neper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dda28c7e43402bbfc5e2314fec6e4c5193a66e95"
libc = "glibc"
os = "linux"

    [[neper.download]]
    sha256 = "c551f3005d01eda0567bfa6f230cbf2efa2d2a5037c6fe66c5eb30571b479569"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[neper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8aeec6a58c78a3bee41524d4bebd91b3ac4de57"
libc = "glibc"
os = "linux"

    [[neper.download]]
    sha256 = "f9516d4e0577fd90cd639e2853e6e46ae36e3de1ebc8a211a0a489b9b7b4512d"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[neper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "efdfc9f7136da13265c998d8d9e0cc022deed4b4"
libc = "glibc"
os = "linux"

    [[neper.download]]
    sha256 = "51624bfe7d3bff594e487c9dc5466719f54aba01f7089345661f220c863e5660"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.i686-linux-gnu-cxx03.tar.gz"
[[neper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a4cf858edd008ef812cb312266ff1a58fe7aaa5"
libc = "glibc"
os = "linux"

    [[neper.download]]
    sha256 = "86db217e7dc595a1751900414f2972547d0f6fa7f056ed127c1449b52900cdf9"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.i686-linux-gnu-cxx11.tar.gz"
[[neper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95ca188882d5d5a69ea978bac6fcc60271c58c79"
libc = "glibc"
os = "linux"

    [[neper.download]]
    sha256 = "5a9ae6122dd954ad1714dba51fc4e291139c6cd357050adbf27ec4c7b307e091"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[neper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b739db37384fdb7b8302614bcbfd5344569e3681"
libc = "glibc"
os = "linux"

    [[neper.download]]
    sha256 = "880864ba5842243d7699a468359bfa04705bc2f6223f14466fa536ae3383b3f5"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[neper]]
arch = "x86_64"
git-tree-sha1 = "6b603763183f0a526674cbd1b6b87c428b69f2c1"
os = "macos"

    [[neper.download]]
    sha256 = "20844ff84515b764338806817c8c25571cf1edede84f8cabe4673c450d890e58"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.x86_64-apple-darwin.tar.gz"
[[neper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f9f9f96905f5cedf166f93e9d2422870d34bd12"
libc = "glibc"
os = "linux"

    [[neper.download]]
    sha256 = "f8468cd37616f7d732332d622728f6b62407487a409732111e771ce4739b151d"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.x86_64-linux-gnu-cxx03.tar.gz"
[[neper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b30a1351399e85e18cd3266ec0035b13f214fba"
libc = "glibc"
os = "linux"

    [[neper.download]]
    sha256 = "ea7db4a01b07d612b1a4a37e14d7f8379436cfb0706ed32b1eeef4d7097ece56"
    url = "https://github.com/JuliaBinaryWrappers/neper_jll.jl/releases/download/neper-v4.8.2+0/neper.v4.8.2.x86_64-linux-gnu-cxx11.tar.gz"
