# Autogenerated wrapper script for neper_jll for i686-linux-gnu-cxx11
export neper

using CompilerSupportLibraries_jll
using GSL_jll
using NLopt_jll
using SCOTCH_jll
using gmsh_jll
JLLWrappers.@generate_wrapper_header("neper")
JLLWrappers.@declare_executable_product(neper)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, GSL_jll, NLopt_jll, SCOTCH_jll, gmsh_jll)
    JLLWrappers.@init_executable_product(
        neper,
        "bin/neper",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
