# Autogenerated wrapper script for neper_jll for x86_64-apple-darwin
export neper

using LLVMOpenMP_jll
using GSL_jll
using NLopt_jll
using SCOTCH_jll
using gmsh_jll
JLLWrappers.@generate_wrapper_header("neper")
JLLWrappers.@declare_executable_product(neper)
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll, GSL_jll, NLopt_jll, SCOTCH_jll, gmsh_jll)
    JLLWrappers.@init_executable_product(
        neper,
        "bin/neper",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
